# Pandas Demonstration

Pandas provides a method that makes it easy to consume CSV content into a pandas DataFrame object, using pd.read_csv().

In [1]:
import pandas as pd
data: pd.DataFrame = pd.read_csv("sample_data.csv")
print(data)

        Name  Age            City
0    Richard   35      Vero Beach
1      Dylan   26       Flossmoor
2    Charles   22      Glen Ellyn
3        Lee   22          Dallas
4     Jaisal   23    Morton Grove
5        Tim   25     West Dundee
6        Ben   23        Atkinson
7       Joey   23         Lasalle
8   Isabelle   22      Long Grove
9        Dio   24          London
10     Lucas   23     Lindenhurst
11      Alec   31     Des Plaines
12     Magan   22    Vernon Hills
13  Danielle   22     Plainfields
14      Andy   24          Darien
15    Andrew   22  East Brunswick

To start working with DataFrames, we can use the head() and tail() methods to get a window into the DataFrame's data. This is especially useful with DataFrames with too many rows of data to easily view at once.

In [2]:
print("DataFrame Head")
print(data.head())
print("\n"*2)
print("DataFrame Tail")
print(data.tail())

DataFrame Head
      Name  Age          City
0  Richard   35    Vero Beach
1    Dylan   26     Flossmoor
2  Charles   22    Glen Ellyn
3      Lee   22        Dallas
4   Jaisal   23  Morton Grove



DataFrame Tail
        Name  Age            City
11      Alec   31     Des Plaines
12     Magan   22    Vernon Hills
13  Danielle   22     Plainfields
14      Andy   24          Darien
15    Andrew   22  East Brunswick

In order to access an individual column, you may index the DataFrame similarly to dictionaries:

In [3]:
city_column: pd.Series = data["Age"]
print(city_column)

0     35
1     26
2     22
3     22
4     23
5     25
6     23
7     23
8     22
9     24
10    23
11    31
12    22
13    22
14    24
15    22
Name: Age, dtype: int64

Pandas provides a method to filter a DataFrame by using boolean expressions:

In [4]:
data[data["Age"] > 24]

       Name  Age         City
0   Richard   35   Vero Beach
1     Dylan   26    Flossmoor
5       Tim   25  West Dundee
11     Alec   31  Des Plaines

In [5]:
# Pandas uses slightly different syntax for using column length
# .str is necessary to treat the column values as strings
data[data["Name"].str.len() < 5]

    Name  Age         City
3    Lee   22       Dallas
5    Tim   25  West Dundee
6    Ben   23     Atkinson
7   Joey   23      Lasalle
9    Dio   24       London
11  Alec   31  Des Plaines
14  Andy   24       Darien

In [14]:
# Along with filtering, we can also sort a DataFrame's rows
sorted_data: pd.DataFrame = data.sort_values(by=['Age', 'Name']) 
print(sorted_data)

        Name  Age            City
15    Andrew   22  East Brunswick
2    Charles   22      Glen Ellyn
13  Danielle   22     Plainfields
8   Isabelle   22      Long Grove
3        Lee   22          Dallas
12     Magan   22    Vernon Hills
6        Ben   23        Atkinson
4     Jaisal   23    Morton Grove
7       Joey   23         Lasalle
10     Lucas   23     Lindenhurst
14      Andy   24          Darien
9        Dio   24          London
5        Tim   25     West Dundee
1      Dylan   26       Flossmoor
11      Alec   31     Des Plaines
0    Richard   35      Vero Beach

Pandas is great for analyzing data, as it provides many analytical functions.

In [7]:
print(f"Mean age: {data["Age"].mean()}")
print(f"Age sum: {data["Age"].sum()}")

Mean age: 24.3125
Age sum: 389

You can also clean data in different ways with Pandas

In [9]:
# Drop a row (Sorry Rich)
for x in sorted_data.index:
    if sorted_data.loc[x, "Age"] > 32:
        sorted_data.drop(x, inplace = True)

# Modify an entry
for x in sorted_data.index:
    if sorted_data.loc[x, "Name"] == "Ben":
        sorted_data.loc[x, "Name"] = "Benjamin"

Now we can easily write this sorted dataframe to a new CSV file

In [10]:
sorted_data.to_csv("sorted_data.csv")